workdir: calset-test
# Configuration of AAOmega
AAOmegaConfig:
  from_rss:
    "/home/pcorchoc/Develop/pykoala-tutorials/tutorials/data/koala/580V/27feb10009red.fits"

# List the corrections that you want to include in the CalibrationSet
CalibrationSet:
  ThroughputCorrection:
  # List the flat fields
    rss_set:
          - "/home/pcorchoc/Develop/pykoala-tutorials/tutorials/data/koala/580V/27feb10009red.fits"
    WaveOffsetCorrect:
      # Waveoffset kwargs
      kwargs:
        plot : True  
    
    # Throuput kwargs
    kwargs:
      medfilt: 20  # Use a median filter to smooth the throughput across the dispersion axis

  AtmosphericExtinctionCorrection:
    file: default

  StandardStarsCal:
    rss_set:
          - "/home/pcorchoc/Develop/pykoala-tutorials/tutorials/data/koala/580V/27feb10028red.fits"
          - "/home/pcorchoc/Develop/pykoala-tutorials/tutorials/data/koala/580V/27feb10029red.fits"
          - "/home/pcorchoc/Develop/pykoala-tutorials/tutorials/data/koala/580V/27feb10030red.fits"
    WaveOffsetCorrect:
      kwargs:
        plot: True
        median_smooth: 10
        pol_fit_deg: 3
